2D Streamer protocol: new functionalities
scipion-em/scipion-em-facilities pull request #30
Opened 2024-04-09 11:04 UTC by danielmarchan3

- Cumulative Batch
- Limit for launching classification jobs

2024-04-10 09:25 UTC, pconesa requested changes
Add a line in changes and review if version should be bumped, please.

2024-04-10 09:44 UTC, danielmarchan3 commented
> Add a line in changes and review if version should be bumped, please.

Line added and version it seems that 3.0.6 is in progress so I added this change on this version. When Alberto comes back we will release this version.

2024-05-21 10:19 UTC, albertmena commented
I'd change the name of the protocol, the monitor functionality is not the main of the protocol, I think "Copy 2d Classification subset" or something similar

2024-05-29 05:56 UTC, albertmena approved these changes

2024-05-29 06:04 UTC, merged